name 'missing_breaking_machine'
maintainer 'Vinicius Stigliani'
maintainer_email 'vinistig@br.ibm.com'
license 'all_rights'
description 'Installs/Configures missing_ruby_machine'
long_description 'Installs/Configures missing_ruby_machine'
version '0.1.0'

depends 'git'
depends 'rvm'
depends 'yum-passenger'
depends 'nginx'
depends 'capistrano'
depends 'rvm_passenger_nginx'
